adding homework dom-practice
Temu4/a-level-fe-homeworks-2022 pull request #113
Opened 2022-05-23 19:29 UTC by tony7kh

2022-06-07 12:20 UTC, Temu4 requested changes
Great job!
Look good from visual perspective!

But there are several things to refactor ⬇️

2022-06-07 12:20 UTC, Temu4 commented on students/tony7kh/dom-practice/README.md
> +https://tony7kh.github.io/dom-practice-v2/
Would you pls prettify this link using Markdown syntax?

2022-06-07 12:20 UTC, Temu4 commented on students/tony7kh/dom-practice/index.html
> +                            <img src="img/A4.png" alt="banner">
`alt="benner"` is useless here. Please add some meaningful text.

2022-06-07 12:20 UTC, Temu4 commented on students/tony7kh/dom-practice/index.html
> +            <section class="section-banner">
If you have just one common content inside `main` tag, you can skip `section` tag from semantic purpose.

2022-06-07 12:20 UTC, Temu4 commented on students/tony7kh/dom-practice/script.js
> +const A4Button = document.getElementById("A4-button");
please name constants start from lowercase letter.

2022-06-07 12:20 UTC, Temu4 commented on students/tony7kh/dom-practice/script.js
> +
Do you see some kind of pattern here to simplify similar code a bit?

2022-06-11 12:27 UTC, tony7kh commented
Could you recheck my updates according to the last commits?

2022-08-07 15:31 UTC, Temu4 requested changes

2022-08-07 15:31 UTC, Temu4 commented on students/tony7kh/dom-practice/index.html
> +    <script src="script.js" type="module"></script>
don't forget to include `utils.js` scripts

2022-08-07 15:31 UTC, Temu4 commented on students/tony7kh/dom-practice/script.js
> +import { navMenu, bannerRow } from '/constants.js';
```suggestion
import { navMenu, bannerRow } from './constants.js';
```

2022-08-07 15:31 UTC, Temu4 commented on students/tony7kh/dom-practice/utils.js
> +import { navMenu, hamburger } from '/constants.js';
```suggestion
import { navMenu, hamburger } from './constants.js';
```

2026-08-11 22:02 UTC, closed without merging