dom-practice
Temu4/a-level-fe-homeworks-2022 pull request #119
Opened 2022-05-25 21:03 UTC by msemerni

2022-06-06 23:45 UTC, Temu4 requested changes
Good job!
From visual perspective looks really interesting.

But there are still several things to refactor ⬇️

2022-06-06 23:45 UTC, Temu4 commented on students/msemerni/dom-practice/README.md
> +[#Demo](https://wwbo9z.csb.app/)
why do you need the second link here?

2022-06-06 23:45 UTC, Temu4 commented on students/msemerni/dom-practice/js/index.js
> +const contentYozhik = "Yozhik is a shy male hedgehog living in the land of Smeshariki. He likes to collect cacti and candy wrappers. His best friend is Krosh. Hedgehog was born on February 14th. Appa
Please consider to move all of these to a single object with content data.

2022-06-06 23:45 UTC, Temu4 commented on students/msemerni/dom-practice/js/index.js
> +function loadHomeContent(contentHome) {
Try to move all function declarations to the top of the file. It could increase code readability

2022-06-06 23:45 UTC, Temu4 commented on students/msemerni/dom-practice/js/index.js
> +  contentDiv.style.backgroundImage = "img/background_home.png";
Consider to change inline styles to a class name with appropriate styles

2022-06-06 23:45 UTC, Temu4 commented on students/msemerni/dom-practice/js/index.js
> +  img.src = imgSrc;
Don’t forget to provide values to `alt` attributes

2022-06-06 23:45 UTC, Temu4 commented on students/msemerni/dom-practice/js/index.js
> +});
Is it possible to avoid several `addEventListeners` with a single one?

2022-06-08 21:11 UTC, msemerni commented on students/msemerni/dom-practice/README.md
> +[#Demo](https://wwbo9z.csb.app/)
Second link - Sandbox

2022-06-09 20:02 UTC, Temu4 requested changes

2022-06-09 20:02 UTC, Temu4 commented on students/msemerni/dom-practice/js/index.js
> +  <div class = "textDiv">
```suggestion
  <div class="textDiv">
```

2022-06-09 20:03 UTC, Temu4 commented
@msemerni looks much-much better, but still needs some improvements 😄

2022-08-07 14:38 UTC, merged