folder name changed to hw-1
Temu4/a-level-fe-homeworks-2022 pull request #12
Opened 2022-04-22 18:26 UTC by msemerni

2022-04-26 13:23 UTC, msemerni commented
hw-2

2022-04-28 18:24 UTC, Temu4 requested changes

2022-04-28 18:24 UTC, Temu4 commented on students/msemerni/hw-1/index.html
> +        let div = document.getElementById("div");
it's better to use `const` instead `let` for the links to DOM elements

2022-04-28 18:24 UTC, Temu4 commented on students/msemerni/hw-1/js/index.js
> +let p2 = document.createElement("p");
The same

2022-05-13 07:40 UTC, Temu4 commented
Hey 👋 
You shouldn't add hw-2/hw-3 here.
Please remove them

2022-05-22 14:52 UTC, Temu4 commented
@msemerni can I help you with something?

2022-05-23 17:22 UTC, closed without merging