add hw-3
Temu4/a-level-fe-homeworks-2022 pull request #30
Opened 2022-04-29 10:33 UTC by AntonBakaiev

2022-05-13 09:58 UTC, Temu4 requested changes

2022-05-13 09:58 UTC, Temu4 commented on students/AntonBakaiev/hw-3/answers_1.md
> +function makeSomeCoolStaff(){
@AntonBakaiev 
Please be aware, that moments when you declare a function and use it are different.

Would you update your answer based on that?

2022-05-14 08:58 UTC, AntonBakaiev commented on students/AntonBakaiev/hw-3/answers_1.md
> +function makeSomeCoolStaff(){
відредактував

2022-05-22 14:39 UTC, Temu4 approved these changes

2022-05-22 14:39 UTC, merged