Hw 5
Temu4/a-level-fe-homeworks-2022 pull request #59
Opened 2022-05-07 13:21 UTC by AntonBakaiev

2022-06-06 21:47 UTC, Temu4 requested changes

2022-06-06 21:47 UTC, Temu4 commented on students/AntonBakaiev/hw-4/answer.js
> +let initialText = prompt('Введите урывок текста');
Please remove files related with previous HW

2022-06-06 21:47 UTC, Temu4 commented on students/AntonBakaiev/hw-5/answer.js
> +    let max = Math.max(...number)
Why not `const`?

2022-06-06 21:47 UTC, Temu4 commented on students/AntonBakaiev/hw-5/answer.js
> +Task 2
```suggestion
// Task 2 
```

2022-06-06 21:47 UTC, Temu4 commented on students/AntonBakaiev/hw-5/answer.js
> +}
```suggestion
function joinObjects(...objects) { 
    const objSum = Object.assign(...objects);
    return objSum;
}
```

2022-06-06 21:47 UTC, Temu4 commented on students/AntonBakaiev/hw-5/answer.js
> +Task 3
```suggestion
// Task 3
```

2022-06-06 21:47 UTC, Temu4 commented on students/AntonBakaiev/hw-5/answer.js
> +    enumerable: false,
Using `Object.defineProperties` `enumerable` would be `false` by default.

2022-06-07 17:15 UTC, AntonBakaiev commented on students/AntonBakaiev/hw-5/answer.js
> +    enumerable: false,
виправив

2022-06-07 17:16 UTC, AntonBakaiev commented on students/AntonBakaiev/hw-5/answer.js
> +Task 3
+

2022-06-07 17:16 UTC, AntonBakaiev commented on students/AntonBakaiev/hw-5/answer.js
> +}
+

2022-06-07 17:16 UTC, AntonBakaiev commented on students/AntonBakaiev/hw-5/answer.js
> +Task 2
+

2022-06-07 17:16 UTC, AntonBakaiev commented on students/AntonBakaiev/hw-5/answer.js
> +    let max = Math.max(...number)
виправив

2022-06-07 17:16 UTC, AntonBakaiev commented on students/AntonBakaiev/hw-5/answer.js
> +Task 1
+

2022-08-07 12:37 UTC, Temu4 approved these changes

2022-08-07 12:37 UTC, merged