hw-6+7
Temu4/a-level-fe-homeworks-2022 pull request #71
Opened 2022-05-12 15:44 UTC by AntonBakaiev

2022-06-06 21:54 UTC, Temu4 requested changes

2022-06-06 21:54 UTC, Temu4 commented on students/AntonBakaiev/hw-6+7/Task-1.js
> +    if (enterNumber == 0) {
Why you use non-strict equality operator here?
```suggestion
    if (enterNumber === 0) {
```

2022-06-06 21:54 UTC, Temu4 commented on students/AntonBakaiev/hw-6+7/Task-1.js
> +    } else if ((enterNumber == 1) || (enterNumber % 3 === 0)) {
```suggestion
    } else if ((enterNumber === 1) || (enterNumber % 3 === 0)) {
```

2022-06-06 21:54 UTC, Temu4 commented on students/AntonBakaiev/hw-6+7/Task-1.js
> +    } else if ((enterNumber == 1) || (enterNumber % 3 === 0)) {
And is current logic correct? What would be the output for `enterNumber = 25`? 😄

2022-06-07 17:45 UTC, AntonBakaiev commented on students/AntonBakaiev/hw-6+7/Task-1.js
> +    } else if ((enterNumber == 1) || (enterNumber % 3 === 0)) {
тепер все вірно працює

2022-06-07 17:45 UTC, AntonBakaiev commented on students/AntonBakaiev/hw-6+7/Task-1.js
> +    if (enterNumber == 0) {
виправив

2022-08-07 13:37 UTC, Temu4 commented on students/AntonBakaiev/hw-6+7/Task-1.js
> +    } else if ((enterNumber == 1) || (enterNumber % 3 === 0)) {
`enterNumber = 49`
`enterNumber = 11`
`enterNumber = 13`
...

2022-08-07 13:38 UTC, merged